# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'youi.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(402, 600)
        MainWindow.setStyleSheet("background-color: fd5b5d")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.nazv = QtWidgets.QLabel(self.centralwidget)
        self.nazv.setGeometry(QtCore.QRect(0, 0, 401, 71))
        font = QtGui.QFont()
        font.setFamily("Rockwell Extra Bold")
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.nazv.setFont(font)
        self.nazv.setStyleSheet("background-color: #722")
        self.nazv.setAlignment(QtCore.Qt.AlignCenter)
        self.nazv.setObjectName("nazv")
        self.cc = QtWidgets.QLineEdit(self.centralwidget)
        self.cc.setGeometry(QtCore.QRect(20, 270, 371, 61))
        self.cc.setStyleSheet("background-color: 34264e")
        self.cc.setObjectName("cc")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(130, 440, 141, 51))
        self.pushButton.setStyleSheet("background-color: 34264e")
        self.pushButton.setObjectName("pushButton")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(90, 220, 211, 31))
        self.label.setStyleSheet("background-color: #ffffff")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.nazv.setText(_translate("MainWindow", "Поиск видео"))
        self.pushButton.setText(_translate("MainWindow", "Искать!"))
        self.label.setText(_translate("MainWindow", "ВВедите название"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
